#!/bin/sh
#
# Blink the blue LED every second


source /leds_gpio.d/leds_gpio.sh

while true; do
	echo 0 > /sys/class/gpio/gpio$blue_led_pin/value
	sleep 1
	echo 1 > /sys/class/gpio/gpio$blue_led_pin/value
	sleep 1
done
