#!/bin/sh
#
# Blink the red and blue LEDs every second


source /hardware_variables.d/leds.sh

while true; do
	echo 0 > /sys/class/gpio/gpio$red_led_pin/value
	sleep 1
	echo 1 > /sys/class/gpio/gpio$red_led_pin/value
	sleep 1

	echo 0 > /sys/class/gpio/gpio$blue_led_pin/value
	sleep 1
	echo 1 > /sys/class/gpio/gpio$blue_led_pin/value
	sleep 1
done
